// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MVC.Controllers
{
	public partial class DashboardController
	{
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public DashboardController() { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected DashboardController(Dummy d) { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoute(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
		{
			return RedirectToAction(taskResult.Result);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
		{
			return RedirectToActionPermanent(taskResult.Result);
		}


		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public DashboardController Actions { get { return MVC.Dashboard; } }
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Area = "";
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Name = "Dashboard";
		[GeneratedCode("T4MVC", "2.0")]
		public const string NameConst = "Dashboard";
		[GeneratedCode("T4MVC", "2.0")]
		static readonly ActionNamesClass s_actions = new ActionNamesClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionNamesClass ActionNames { get { return s_actions; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNamesClass
		{
			public readonly string Index = "Index";
			public readonly string LaadGrafiekAanpassen = "LaadGrafiekAanpassen";
			public readonly string LaadLegePartialView = "LaadLegePartialView";
			public readonly string LaadGeavanceerdeInstellingen = "LaadGeavanceerdeInstellingen";
			public readonly string LaadGrafiekToevoegen = "LaadGrafiekToevoegen";
			public readonly string LaadTop5 = "LaadTop5";
			public readonly string LaadStaafdiagram = "LaadStaafdiagram";
			public readonly string LaadStaafdiagramMulti = "LaadStaafdiagramMulti";
			public readonly string LaadDonutdiagram = "LaadDonutdiagram";
			public readonly string LaadAlleGrafieken = "LaadAlleGrafieken";
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNameConstants
		{
			public const string Index = "Index";
			public const string LaadGrafiekAanpassen = "LaadGrafiekAanpassen";
			public const string LaadLegePartialView = "LaadLegePartialView";
			public const string LaadGeavanceerdeInstellingen = "LaadGeavanceerdeInstellingen";
			public const string LaadGrafiekToevoegen = "LaadGrafiekToevoegen";
			public const string LaadTop5 = "LaadTop5";
			public const string LaadStaafdiagram = "LaadStaafdiagram";
			public const string LaadStaafdiagramMulti = "LaadStaafdiagramMulti";
			public const string LaadDonutdiagram = "LaadDonutdiagram";
			public const string LaadAlleGrafieken = "LaadAlleGrafieken";
		}


		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/Dashboard/Index.cshtml";
		}
	}

	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public partial class T4MVC_DashboardController : MVC.Controllers.DashboardController
	{
		public T4MVC_DashboardController() : base(Dummy.Instance) { }

		[NonAction]
		partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Index()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
			IndexOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadGrafiekAanpassenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadGrafiekAanpassen()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadGrafiekAanpassen);
			LaadGrafiekAanpassenOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadLegePartialViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadLegePartialView()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadLegePartialView);
			LaadLegePartialViewOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadGeavanceerdeInstellingenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadGeavanceerdeInstellingen()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadGeavanceerdeInstellingen);
			LaadGeavanceerdeInstellingenOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadGrafiekToevoegenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadGrafiekToevoegen()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadGrafiekToevoegen);
			LaadGrafiekToevoegenOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadTop5Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadTop5()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadTop5);
			LaadTop5Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadStaafdiagramOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadStaafdiagram()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadStaafdiagram);
			LaadStaafdiagramOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadStaafdiagramMultiOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadStaafdiagramMulti()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadStaafdiagramMulti);
			LaadStaafdiagramMultiOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadDonutdiagramOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadDonutdiagram()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadDonutdiagram);
			LaadDonutdiagramOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadAlleGrafiekenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadAlleGrafieken()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadAlleGrafieken);
			LaadAlleGrafiekenOverride(callInfo);
			return callInfo;
		}

	}
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
