// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MVC.Controllers
{
	public partial class SuperAdminController
	{
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public SuperAdminController() { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected SuperAdminController(Dummy d) { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoute(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
		{
			return RedirectToAction(taskResult.Result);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
		{
			return RedirectToActionPermanent(taskResult.Result);
		}


		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public SuperAdminController Actions { get { return MVC.SuperAdmin; } }
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Area = "";
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Name = "SuperAdmin";
		[GeneratedCode("T4MVC", "2.0")]
		public const string NameConst = "SuperAdmin";
		[GeneratedCode("T4MVC", "2.0")]
		static readonly ActionNamesClass s_actions = new ActionNamesClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionNamesClass ActionNames { get { return s_actions; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNamesClass
		{
			public readonly string Index = "Index";
			public readonly string LaadGemonitordeItemsBeheren = "LaadGemonitordeItemsBeheren";
			public readonly string LaadData = "LaadData";
			public readonly string LaadGebruikersactiviteit = "LaadGebruikersactiviteit";
			public readonly string LaadLayout = "LaadLayout";
			public readonly string LaadMediabronnen = "LaadMediabronnen";
			public readonly string LaadGebruikersgegevens = "LaadGebruikersgegevens";
			public readonly string LaadDeelplatform = "LaadDeelplatform";
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNameConstants
		{
			public const string Index = "Index";
			public const string LaadGemonitordeItemsBeheren = "LaadGemonitordeItemsBeheren";
			public const string LaadData = "LaadData";
			public const string LaadGebruikersactiviteit = "LaadGebruikersactiviteit";
			public const string LaadLayout = "LaadLayout";
			public const string LaadMediabronnen = "LaadMediabronnen";
			public const string LaadGebruikersgegevens = "LaadGebruikersgegevens";
			public const string LaadDeelplatform = "LaadDeelplatform";
		}


		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/SuperAdmin/Index.cshtml";
		}
	}

	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public partial class T4MVC_SuperAdminController : MVC.Controllers.SuperAdminController
	{
		public T4MVC_SuperAdminController() : base(Dummy.Instance) { }

		[NonAction]
		partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Index()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index, "https");
			IndexOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadGemonitordeItemsBeherenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadGemonitordeItemsBeheren()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadGemonitordeItemsBeheren, "https");
			LaadGemonitordeItemsBeherenOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadData()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadData, "https");
			LaadDataOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadGebruikersactiviteitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadGebruikersactiviteit()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadGebruikersactiviteit, "https");
			LaadGebruikersactiviteitOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadLayoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadLayout()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadLayout, "https");
			LaadLayoutOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadMediabronnenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadMediabronnen()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadMediabronnen, "https");
			LaadMediabronnenOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadGebruikersgegevensOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadGebruikersgegevens()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadGebruikersgegevens, "https");
			LaadGebruikersgegevensOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void LaadDeelplatformOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult LaadDeelplatform()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LaadDeelplatform, "https");
			LaadDeelplatformOverride(callInfo);
			return callInfo;
		}

	}
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
