// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
	public class SharedController
	{

		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string AdminKnoppen = "AdminKnoppen";
                public readonly string AdminSuperadminScripts = "AdminSuperadminScripts";
                public readonly string BeheerScripts = "BeheerScripts";
                public readonly string Bewerkingsknop = "Bewerkingsknop";
                public readonly string CheckEmailPrompt = "CheckEmailPrompt";
                public readonly string DataImporterenEnExporteren = "DataImporterenEnExporteren";
                public readonly string DeelplatformAanmaken = "DeelplatformAanmaken";
                public readonly string Donutdiagram = "Donutdiagram";
                public readonly string DonutdiagramMulti = "DonutdiagramMulti";
                public readonly string Error = "Error";
                public readonly string GebruikersactiviteitMonitoren = "GebruikersactiviteitMonitoren";
                public readonly string GebruikersgegevensNakijken = "GebruikersgegevensNakijken";
                public readonly string GemonitordeItemsBeheren = "GemonitordeItemsBeheren";
                public readonly string Getal = "Getal";
                public readonly string GetalTrend = "GetalTrend";
                public readonly string GrafiekAanpassen = "GrafiekAanpassen";
                public readonly string Grafieken = "Grafieken";
                public readonly string GrafiekToevoegen = "GrafiekToevoegen";
                public readonly string HorizontaalStaafdiagram = "HorizontaalStaafdiagram";
                public readonly string HorizontaalStaafdiagramMulti = "HorizontaalStaafdiagramMulti";
                public readonly string LayoutAanpassen = "LayoutAanpassen";
                public readonly string LegePartialView = "LegePartialView";
                public readonly string Lijndiagram = "Lijndiagram";
                public readonly string LijndiagramMulti = "LijndiagramMulti";
                public readonly string Organisaties = "Organisaties";
                public readonly string Personen = "Personen";
                public readonly string SocialeMediabronnenInstellen = "SocialeMediabronnenInstellen";
                public readonly string Staafdiagram = "Staafdiagram";
                public readonly string StaafdiagramMulti = "StaafdiagramMulti";
                public readonly string Taartdiagram = "Taartdiagram";
                public readonly string TaartdiagramMulti = "TaartdiagramMulti";
                public readonly string Termen = "Termen";
                public readonly string Themas = "Themas";
                public readonly string Top10 = "Top10";
                public readonly string Top5 = "Top5";
                public readonly string VerwijderKnop = "VerwijderKnop";
                public readonly string ZoekfunctieGrafieken = "ZoekfunctieGrafieken";
            }
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string AdminKnoppen = "~/Views/Shared/AdminKnoppen.cshtml";
            public readonly string AdminSuperadminScripts = "~/Views/Shared/AdminSuperadminScripts.cshtml";
            public readonly string BeheerScripts = "~/Views/Shared/BeheerScripts.cshtml";
            public readonly string Bewerkingsknop = "~/Views/Shared/Bewerkingsknop.cshtml";
            public readonly string CheckEmailPrompt = "~/Views/Shared/CheckEmailPrompt.cshtml";
            public readonly string DataImporterenEnExporteren = "~/Views/Shared/DataImporterenEnExporteren.cshtml";
            public readonly string DeelplatformAanmaken = "~/Views/Shared/DeelplatformAanmaken.cshtml";
            public readonly string Donutdiagram = "~/Views/Shared/Donutdiagram.cshtml";
            public readonly string DonutdiagramMulti = "~/Views/Shared/DonutdiagramMulti.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string GebruikersactiviteitMonitoren = "~/Views/Shared/GebruikersactiviteitMonitoren.cshtml";
            public readonly string GebruikersgegevensNakijken = "~/Views/Shared/GebruikersgegevensNakijken.cshtml";
            public readonly string GemonitordeItemsBeheren = "~/Views/Shared/GemonitordeItemsBeheren.cshtml";
            public readonly string Getal = "~/Views/Shared/Getal.cshtml";
            public readonly string GetalTrend = "~/Views/Shared/GetalTrend.cshtml";
            public readonly string GrafiekAanpassen = "~/Views/Shared/GrafiekAanpassen.cshtml";
            public readonly string Grafieken = "~/Views/Shared/Grafieken.cshtml";
            public readonly string GrafiekToevoegen = "~/Views/Shared/GrafiekToevoegen.cshtml";
            public readonly string HorizontaalStaafdiagram = "~/Views/Shared/HorizontaalStaafdiagram.cshtml";
            public readonly string HorizontaalStaafdiagramMulti = "~/Views/Shared/HorizontaalStaafdiagramMulti.cshtml";
            public readonly string LayoutAanpassen = "~/Views/Shared/LayoutAanpassen.cshtml";
            public readonly string LegePartialView = "~/Views/Shared/LegePartialView.cshtml";
            public readonly string Lijndiagram = "~/Views/Shared/Lijndiagram.cshtml";
            public readonly string LijndiagramMulti = "~/Views/Shared/LijndiagramMulti.cshtml";
            public readonly string Organisaties = "~/Views/Shared/Organisaties.cshtml";
            public readonly string Personen = "~/Views/Shared/Personen.cshtml";
            public readonly string SocialeMediabronnenInstellen = "~/Views/Shared/SocialeMediabronnenInstellen.cshtml";
            public readonly string Staafdiagram = "~/Views/Shared/Staafdiagram.cshtml";
            public readonly string StaafdiagramMulti = "~/Views/Shared/StaafdiagramMulti.cshtml";
            public readonly string Taartdiagram = "~/Views/Shared/Taartdiagram.cshtml";
            public readonly string TaartdiagramMulti = "~/Views/Shared/TaartdiagramMulti.cshtml";
            public readonly string Termen = "~/Views/Shared/Termen.cshtml";
            public readonly string Themas = "~/Views/Shared/Themas.cshtml";
            public readonly string Top10 = "~/Views/Shared/Top10.cshtml";
            public readonly string Top5 = "~/Views/Shared/Top5.cshtml";
            public readonly string VerwijderKnop = "~/Views/Shared/VerwijderKnop.cshtml";
            public readonly string ZoekfunctieGrafieken = "~/Views/Shared/ZoekfunctieGrafieken.cshtml";
		}
	}

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
